name: Build

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# Controls when the action will run.
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2021.3.16f1
        targetPlatform:
         - WebGL
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      with:
        lfs: true
        clean: false
        fetch-depth: 0

#     Cache
    - uses: actions/cache@v3.3.1
      with:
        path: Library
        key: Library
        restore-keys: Library-

    # Build
    - name: Build project
      uses: game-ci/unity-builder@v2.2.0
      with:
        unityVersion: ${{ matrix.unityVersion }}
        targetPlatform: ${{ matrix.targetPlatform }}

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        branch: gh-pages
        folder: build/${{ matrix.targetPlatform }}

    # Output
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: Build-${{ matrix.targetPlatform }}
        path: build/${{ matrix.targetPlatform }}