name: Build

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# Controls when the action will run. 
on: 
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  # Triggers the workflow on push or pull request events but only for the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2022.2.0f1
        targetPlatform:
         - WebGL
    steps:
    - name: Checkout
      uses: actions/checkout@v3.2.0
      with:
        lfs: true
        clean: false
        
#     Cache
    - uses: actions/cache@v3
      with:
        path: Library
        key: Library

    # Build
    - name: Build project
      uses: game-ci/unity-builder@v2.1.2
      with:
        unityVersion: ${{ matrix.unityVersion }}
        targetPlatform: ${{ matrix.targetPlatform }}

    # Output
    - uses: actions/upload-artifact@v3.1.1
      with:
        name: Build-${{ matrix.targetPlatform }}
        path: build/${{ matrix.targetPlatform }}
