name: Create Release Note

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          name: ${{ github.event.pull_request.body }}
          tag_name: ${{ github.event.pull_request.title }}